### ISSUE TITLE
Formspree

### ISSUE THREAD

**Issue by mato0039** [mato0039/registration-form#1]
Hi Christina

Markbot is still giving me the error message about website link in the form field.

Do you have any idea how to fix this?

<img width="1027" alt="Screen Shot 2020-03-11 at 12 53 54 PM" src="https://user-images.githubusercontent.com/55108737/76442473-61307a80-6397-11ea-9414-64f1df7831e9.png">

Thanks 

Cathy

@muxlowc

**Comment by muxlowc** [comment]
@mato0039 hmm so i just tried on my end and it seemed to work when i put POST in capital letters
But i'll copy exactly what I have, just in case:

method="POST" action="https://formspree.io/bradlet@algonquincollege.com"

If it's still not working, I'll give you the mark on my end because I think this could be a weird glitch :(

**Comment by mato0039** [comment]
That worked! Finallaaaaayyyyyyy.....lol.

Thank you! 😊
